#!/bin/bash
VERSION=0.1.3

Usage(){
	echo ""
	echo "This command will create the directory structure and the configuration files for each comparisons."
	echo ""
	echo "Usage:"
	echo "	Venn-Tool init"
	echo ""
	echo "		data_directory: The directory that contains all the lists to compare."
	echo "		config.txt: A configuration file listing which samples to compare (see Documentation/config.txt)."
	echo "			    Default: config.txt"
	echo ""
	echo "Available commands:"
	echo "	help"
	echo "	version"
	echo ""
}

if [ "$#" -lt 1 ] || [ "$1" == "help" ]
then
	Usage
	exit
elif [ "$1" == "version" ]
then
	echo "Version: $VERSION"
fi

dir_scripts=$1
dir_data=$2
config_file=$3

# Validate parameter
if [ "$dir_data" == "" ]
then
	dir_data=data
fi

if [ ! -d "$dir_data" ]
then
	echo ""
	echo "Data directory does not exists: $dir_data"
	Usage
	exit
fi

if [ "$config_file" == "" ]
then
	config_file=config.txt
fi

if [ ! -e "$config_file" ]
then
	echo ""
	echo "Cannot find configuration file: $config_file"
	Usage
	exit
fi

# Reset main directory's Makefile
rm -f Makefile

# For each combination in the config.txt file
while read line
do
        # Create a subdirectory in results directory
	subdirectory=results/$(echo $line | sed "s/ /_/g")
        mkdir -p $subdirectory/data

        # Create the Makefile for the subdirectory
        rm -f $subdirectory/Makefile
	for file in $line
        do
                echo DATA+="$file " >> $subdirectory/Makefile
        done
	echo "" >> $subdirectory/Makefile
	for file in $($dir_scripts/Utility/generateVennXML.py -p $line)
	do
		echo LISTS+=$file >> $subdirectory/Makefile
	done

	# Add the css dependencies
	echo "" >> $subdirectory/Makefile
	sample_count=$(echo $line | awk '{ print NF }')
	echo "CSS_FILES+=venn$sample_count.css" >> $subdirectory/Makefile

	# Convert the subdirectory's template with real values
        sed_dir_scripts=$(echo $dir_scripts| sed 's/\//\\\//g')
        sed_dir_data=$(echo $dir_data| sed 's/\//\\\//g')
        base_targets=$(echo $files | sed 's/\t/ /g')
        cat $dir_scripts/Templates/Makefile_SubDirectories_Template \
        | sed "s/__DIR_SCRIPTS__/$sed_dir_scripts/g" \
        | sed "s/__DIR_DATA_SOURCE__/\.\.\/\.\.\/$sed_dir_data/g" \
        | sed "s/__BASE_TARGET__/$(basename $subdirectory)/g" \
        >> $subdirectory/Makefile

        # Add the subdirectory to main Makefile
        echo SUBDIRS+=$subdirectory >> Makefile

done < config.txt

# Complete the main makefile
echo "" >> Makefile
for file in $(ls $dir_scripts/Stylesheets/css*)
do
	echo "CSS_FILES+=$file" >> Makefile
done

sed_dir_data=$(echo $dir_data | sed 's/\//\\\//g')
cat $dir_scripts/Templates/Makefile_MainDirectory_Template \
| sed "s/__DIR_DATA__/$sed_dir_data/g" \
| sed "s/__DIR_SCRIPTS__/$sed_dir_scripts/g" \
>> Makefile
